### PR TITLE
Update yurt-edgex-manager to support kubernetes 1.22+

### LINKED ISSUE #21: Update yurt-edgex-manager to support kubernetes 1.22+

### PR DESCRIPTION
**Pull request by Lavender-QAQ**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Support kubernetes1.22+
Fixed printcolumn bug caused by changing crd name

#### Which issue(s) this PR fixes:
Fixes #21

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by lwmqwer** [comment]
We should upgrade the E2E test to kubernetes 1.22 as well

**Comment by Lavender-QAQ** [comment]
Because yurt-app-manager reported an error on 1.25, the version of the kind node image was changed to 1.24.4.

**Review by lwmqwer — APPROVED** [review]
/lgtm

**Review by lwmqwer — APPROVED** [review]
/lgtm

**Pull request merged**
